### ISSUE TITLE
Koa support

### ISSUE THREAD

**Issue by thaume** [jaredhanson/oauth2orize#100]
Hey @jaredhanson, thanks for all those authentication modules they're awesome; I've been use them for a strong 2 years with no problems, thanks man.

I am working on a Koa API these days which uses `oauth2orize`, and I was wondering if I should push some PRs' over here or focus on the `koa-auth2orize` port (still in its early stages). If you have any plan in mind, let me know!

Thanks

**Comment by ButuzGOL** [comment]
+1

**Comment by jaredhanson** [comment]
If you send PRs, I'll review them.  My personal preference would be that koa support could be provided by a wrapper layer that calls into `oauth2orize` using traditional `req, res, next` calling convention.  Anything that can be done in an adapter like that, I'd would not accept in a pull request.  If there's anything that can't be done in an adapter, then I'd be open to considering it.

**Comment by casoetan** [comment]
@jaredhanson How do I implement the wrapper you mentioned. A guide will be very perfect. Being battling with this for upwards to 2 days now.
