### ISSUE TITLE
Transfer Ownership, Bless a Fork

### ISSUE THREAD

**Issue by coolaj86** [jaredhanson/oauth2orize#108]
Hey Jared,

It seems like you're not maintaining this project anymore, and there are a growing number of forks with one-off bug fixes that aren't converging.

I feel like I have a good understanding of how the code works and I'd like to take ownership, as my next round of oauth-related work begins this week.

Please allow me to publish updates on npm:

```bash
npm owner add coolaj86 oauth2orize
```

And either:

1. And add me as a collaborator: https://github.com/jaredhanson/oauth2orize/settings/collaboration
2. Transfer ownership to me: https://github.com/jaredhanson/oauth2orize/settings
3. Let people know in the README that I'm actively using and interested in maintaining this: https://github.com/jaredhanson/oauth2orize/pull/107

Thanks for the hard work!

**Comment by davidkalosi** [comment]
+1 on this. if this is going to work please take care of the openid connect extensions as well.

**Comment by tellnes** [comment]
+1 I've been thinking about making a fork myself for the exact same reason. This is also true for other passport related modules.

What about moving to a dedicated Github org and do all passport related stuff there? Passport and related modules is great and it is a pity that a lot of the modules does not get the attention they deserve.

Btw, maybe this should be opened at the passport issue tracker since it applies to more than oauth2orize and it is more likely that @jaredhanson sees it there.

**Comment by davidkalosi** [comment]
an organization would be awesome, I would gladly participate to maintain the modules as well. We are using the oauth2orize modules in one startup - I have adopted some additional features for the modules like token revocation, userinfo endopoint + opeind discoverability - if interested I will gladly share them with the public. 

ping @jaredhanson what to you think about this all ? you have done a lot of cool stuff with the passport and oauth2orize it would be a shame seeing it fade away

david

**Comment by tellnes** [comment]
While we are waiting for @jaredhanson to shim in, we can start discuss where we want to go.

I suggest we fork those modules we want to maintain to a github org and add those who want to contribute to that org. Starting with use three who is active in this issue. Hopefully will @jaredhanson bless it so we do not need to publish updates under another name.

I propose the name `jsauth` inspired by `jshttp` used by the express folks.

**Comment by davidkalosi** [comment]
The cleanest way would be that jared creates an organization and moves all the related repositories there. from that point we can appoint maintainers etc...

I would really try to avoid forking and re-realising the same stuff under different names, the continuity should be there. 

@jaredhanson if you've got a sec please try to chime in, that would be cool :)

**Comment by tellnes** [comment]
Off course the best solution is that jared moves the related repositories to an org and give someone access, but while we wait, it should not stop us from starting coding or creating the org.

Maybe we should try to contact jared by some other means than mentioning him here at github?

**Comment by davidkalosi** [comment]
I have written him an email a couple of months ago and the response was swift. 
So we should start there

**Comment by jaredhanson** [comment]
I'm going to be refocusing my efforts on auth-related projects in the next couple of weeks.  I intend to review and merge most of the outstanding pull requests.

**Comment by tellnes** [comment]
Cool. Do you mind consider adding some people as contributors to some of the modules? This is git, so if you do not like what they do then you can just revert it.

**Comment by Nijikokun** [comment]
> I'm going to be refocusing my efforts on auth-related projects in the next couple of weeks. I intend to review and merge most of the outstanding pull requests.

Please add maintainers so this is maintained while you are busy elsewhere. @jaredhanson

**Comment by coolaj86** [comment]
At my old job we used to have a "bug mug". If you broke the build you had to put a dollar in.

For quality control we could just make every maintainer use passport to connect to stripe payments get charged if they're the `git blame` on failed CI, y'know?

Unless that maintainer breaks the passport module...


j/k j/k :p

**Comment by Windsock** [comment]
I'm really interested myself in becoming a maintainer/contributor, this seems like a fun project to work on.

**Comment by gabrieleds** [comment]
+1
I had to fork passport for tiny changes too
https://github.com/gabrieleds/passport/commit/5f9775ccfda8af4bf8f570795106a38832a89b67
https://github.com/gabrieleds/passport-remember-me/commit/607e072c2893ec5b190f9ea17d4c48ffee64b1ae

**Comment by jaredhanson** [comment]
@gabrieleds Please open pull requests for discussion about your specific changes.  A couple comments:

1. on passport: why is passing req, res to the callback necessary?  When using custom callbacks, you should be executing in a context that already has access to them (ie, a middleware function).

2. on passport-remember-me: this looks good, I'd merge it if you make the option `passReqToCallback` (instead of `passReq`), to match the other strategies.

**Comment by jaredhanson** [comment]
@coolaj86 Thanks for your patches!  I've added you as a collaborator to the repo.  For now, I'm maintaining sole owner rights on npm (I just want a chance to review things before they get released to the wild).

Closing this issue, as I've reallocated my time so I can make sure Passport and OAuth2orize get the attention they need.  If anyone has specific concerns with Passport or individual strategies, please discuss them on the relevant GitHub project.  Thanks!

**Comment by tellnes** [comment]
Thanks for adding a new contributor. That will probably make sure that the project does not die when you are not available. And it is perfectly understandable that you want to review things before they get released to the wild. We are talking about security here, so thats probably a god thing.
