### ISSUE TITLE
Better Documentation.

### ISSUE THREAD

**Issue by Nijikokun** [jaredhanson/oauth2orize#109]
Seriously, 90% of my time was spent reading the source code, which to be honest is a real pain to read in the first place.

Better documentation, in written form (not code) with actual examples of requests being made. (for example the `refresh_token` and `access_token` would be extremely beneficial to anyone who wishes to use this library.)

A good example of undocumented features is the `validate` and `immediate` methods you can pass to `Server.authorization` to handle immediate authorization of a user, and the flow.

1. `Server.authorization` calls `validate` (and checks arity, giving extra arguments up to 5 arity (2 is best imo, you get everything, less confusion))
2. `validate` executes and takes actions
3. `validate` on success calls `immediate` with the user as the second argument
4. `immediate` by default returns false (always showing dialog), if you return true in the second argument it will skip the dialog, automatically authorizing the decision (do any actions here that you would in the decision callback otherwise they will not be invoked).

This is just one example of the many edge cases...

**Comment by jaredhanson** [comment]
Feel free to write this up a form you think would help others.  I'll merge it or link to it.

**Comment by steve-taylor** [comment]
> I'll merge it or link to it.

You have open PRs going back to 2013.
