### ISSUE TITLE
Help with grant password

### ISSUE THREAD

**Issue by ghost** [jaredhanson/oauth2orize#11]
Not sure if your library has implemented it, but I would like to use the password grant to get a token without having to pop open a window in iOS, (SSO) which will allow you to put in your username and password and in a request object send over the username, password, clientID, clientSecret and receive an access token.  This will also help with my previous "auto-approve" ticket....

**Comment by franklinjavier** [comment]
@ghost @jordidiaz @anderson916 
How did you solve this?
