### ISSUE TITLE
error_description should be configurable

### ISSUE THREAD

**Issue by onury** [jaredhanson/oauth2orize#120]
According to the [specs](https://tools.ietf.org/html/rfc6749#section-5.2); the (optional) `error_description` parameter can be set to **any** human-readable ASCII. 

But for example, when resource owner password flow fails after credentials validation we always get error description `"Invalid resource owner credentials"` because it's hard-coded in [password.js#L107](https://github.com/jaredhanson/oauth2orize/blob/master/lib/exchange/password.js#L107).

Sometimes, the reason for responding with `"invalid_grant"` is NOT _Invalid resource owner credentials_. The credentials might be verified OK but the user account could be inactive or suspended. 

The only way to indicate this to the client is the **error_description** property. So this should be configurable.

**Comment by tellnes** [comment]
There is a solution for this in #121, so this can be closed.
