### ISSUE TITLE
Is session transaction_id necessary?

### ISSUE THREAD

**Issue by mrvisser** [jaredhanson/oauth2orize#123]
Is the `transaction_id` really adding more security, given oauth2orize already requires a valid user session during the decision phase?

My understanding of OAuth 2.0 was that shared state isn't necessary, and so I suspect the temporary `transaction_id` credential is unnecessary.

**Comment by jaredhanson** [comment]
It's not for security. The server itself may have many users doing an Oauth flow at the same time. The users themselves may also have multiple flows in a single session (think tabbed browsers authorizing different apps) The transaction id identifies those flows.

**Comment by mrvisser** [comment]
Would it make sense to put serialization/deserialization of the "transaction" into the hands of the consumer, so that session data isn't necessary? This kind of thing seems like it can be done with the query string.

**Comment by jaredhanson** [comment]
It is in the hands of the consumer.  The requirement is that a transaction_id is provided when the user submits an authorization response.  That can be sent in a form post, in the body, or in the query string.  `oauth2orize` doesn't render the dialog, so its up to you how this is submitted.

**Comment by jaredhanson** [comment]
The session data is necessary because you don't want the user to be able to modify the original request made by the OAuth client.  That data needs to be stored in a trusted location, and not self-asserted by the user.

**Comment by mrvisser** [comment]
(I would be happy to PR these suggestions)

**Comment by mrvisser** [comment]
> It is in the hands of the consumer.

How the `transaction_id` is provided is in the hands of the consumer, but I was suggesting the serialization/deserialization of the actual `transaction` data. Rather than always require a session, someone could use their own (stateless) strategy if they wished (e.g., request body params, etc...) rather than requiring that shared state is used. It could default to using a `transaction_id`.

And just to make sure we're on the same page, the concern is that a user will reach into a form, the query string, or fabricate a POST request that performs an authorization decision?

**Comment by jaredhanson** [comment]
Yes, if you want a stateless approach, you still need to ensure that the user cannot tamper with the original parameters of the authorization request.  This is possible, of course, but you'll need to ensure that as the state is passed back and forth between the client and server, that it is signed or encrypted to prevent tampering.

The concern isn't that the user will fabricate a response for an authorization decision (that is the user's decision anyway, so they can specify whatever they want).  The concern is that the user should not modify the original authorization request made by the client.

I'd be happy to review any pull request that would enable stateless operation.

**Comment by mrvisser** [comment]
> I'd be happy to review any pull request that would enable stateless operation.

That's great, I'll start working on something.

> The concern isn't that the user will fabricate a response for an authorization decision
> The concern is that the user should not modify the original authorization request made by the client

I'm sure I understand the value in doing this. There doesn't seem to be anything that can be done maliciously by tampering that data? IIUC, OAuth 2.0 purposely relaxes the constraint of having authentic client authorization request data (e.g., this is why the auth requests are no longer signed).

In the current oauth2orize implementation, anything a user might want to do by tampering the original client data in the decision, they can simply do by re-invoking their own authorization request with the same client_id and getting a new `transaction_id` any way. And if it's not the user doing it, who is tampering the client auth request data?

Either way, if we implement `serializeTransaction` and `deserializeTransaction`, I think we can bypass any disagreement we have here and make things more flexible. I would just request that your review process doesn't enforce having a guarantee that there is client auth request data tampering protection. It would allow for "at your own risk" implementation of transaction (de)serialization.

**Comment by jaredhanson** [comment]
> There doesn't seem to be anything that can be done maliciously by tampering that data?

Yes and no.  I agree that OAuth 2.0 relaxes many of these constraints, and users can "pretend" to be client by re-invoking their own authorization request.

One aspect that is used for security purposes is the redirectURI.  That is validated as belonging to the client when the authorization request is submitted, and used later when redirecting the user and when the client exchanges an authorization code for an access token.  If that redirectURI were allowed to be tampered with during the user's authorization response, you run the risk turning the OAuth server into an open redirector (at best) and not properly verifying later steps when the code is exchanged for a token (at worst).

> . I would just request that your review process doesn't enforce having a guarantee that there is client auth request data tampering protection. It would allow for "at your own risk" implementation of transaction (de)serialization.

I'm not going to guarantee this.  Security is a very important thing, and anything that encourages less secure implementation is not something I want to make easier.  I'm willing to tolerate a certain amount of this, but not when it comes to highly sensitive parts of the protocol such as the redirect URI.

**Comment by coolaj86** [comment]
+1 for removing the need for cookies, I was about to do that myself.

While you're at it, consider that the entire authorization dialog flow can actually be done on the client (as long as there is a shared secret when the user logs in to create JWT-style tokens).

What I'm working on right now is pulling what @substack does with keyboot https://github.com/substack/keyboot into the OAuth2 process - so the server can act as a backup of the user's permissions rather than the owner.

Also, I'm working on OAuth3.org - taking all of the garbage out of OAuth2 so that all you need in order to connect to a consumer is the end-user-facing URL and to accept a license agreement - absolutely no knowledge of implementation details and 0 server requests to complete the process for the typical implicit grant use case.

**Comment by mrvisser** [comment]
> If that redirectURI were allowed to be tampered with during the user's authorization response, you run the risk turning the OAuth server into an open redirector

Protection for the redirectURI actually doesn't happen in this manner. A client is registered with the oauth2 server with one or more valid redirect URIs. The only case a redirect_uri is passed in the grant process is if the server has multiple registered redirect_uri's, but either way we aren't dealing with an open redirect attack.

This kind registered URI protection is being offloaded to the consumer anyway, so IMHO it should be OK to also allow the consumer so implement a relaxed client request authenticity. That said, I am still happy to leave the protected `transaction_id` approach as the default.

**Comment by jaredhanson** [comment]
> The only case a redirect_uri is passed in the grant process is if the server has multiple registered redirect_uri's, but either way we aren't dealing with an open redirect attack.

That depends on the implementation.  I'm just pointing it out as a particular point to consider from a security perspective.  If the user can modify the binding of the code to the redirect URI, that is a potential attack surface.  So, that is one area I would pay particular attention to when reviewing.

**Comment by mrvisser** [comment]
> That depends on the implementation.

It's not just implementation-specific, it's part of the spec (https://tools.ietf.org/html/rfc6749#section-3.1.2.2 , https://tools.ietf.org/html/rfc6749#section-3.1.2.4). I suspect it is one of the requirements introduced in OAuth 2.0 that specifically made it OK to relax client request authenticity.

**Comment by mrvisser** [comment]
I should note that I understand that since oauth2orize doesn't have support to ensure validated `redirect_uri`'s are supported, you are very hesitant to remove client authenticity restrictions. I'm of the opinion that a comment in the docs may be sufficient to make a consumer aware of the issue, similar to https://github.com/jaredhanson/oauth2orize/blob/master/examples/all-grants/oauth2.js#L176-L179

**Comment by jaredhanson** [comment]
I don't entirely follow why you think redirect URIs are less important. Regardless, feel free to implement your ideas, which should help clarify any misunderstanding

**Comment by mrvisser** [comment]
Redirect URI's aren't less important, rather it is not important to verify client request authenticity with them because they are validated against back-end server values that were added when the client was registered, as per the spec.

I register ClientA with valid redirect uri: `www.clienta.com/oauth/cb` on the oauth2server. It is not possible to tamper the authorization redirect URI to be `www.dangerouswebsite.com`, because the redirect is only allowed to be `www.clienta.com/oauth/cb`.

This validation has to happen on the server side regardless of whether or not the client authenticity was kept intact. ClientA is not allowed to send an authorization request that has redirectURI `www.clienta.com/oauth/anothercb` even if it is kept authentic.

They are important, their security is just simply not dependent on client authorization request authenticity.

**Comment by jaredhanson** [comment]
> it is not important to verify client request authenticity with them because they are validated against back-end server values that were added when the client was registered, as per the spec.

That is just one option.  The spec also allows them to be sent in the request, in which case they must be verified correctly.  Security concerns must satisfy the most general case, not the most restricted one.

**Comment by jaredhanson** [comment]
Due to security concerns, most clients **do** sending the redirect URI.  OpenID Connect makes the `redirect_uri` parameter REQUIRED, as noted here:

http://openid.net/specs/openid-connect-core-1_0.html#AuthRequest

**Comment by jaredhanson** [comment]
Here is where the OpenID Connect spec makes note of the difference.  It is valid for any OpenID Connect server to treat the lack of a redirect_uri parameter as an error, and fail both authentication and authorization:

http://openid.net/specs/openid-connect-core-1_0.html#TokenRequestValidation

**Comment by mrvisser** [comment]
@jaredhanson it's not required for security, it's only required because OpenID providers can have multiple valid redirect URI's registered for them:

`This URI MUST exactly match one of the Redirection URI values for the Client pre-registered at the OpenID Provider`

As you can see, since the specified URI MUST match a pre-registered URI, there is still no vector for open redirect attack. It is required to support the feature of having multiple registered Redirect URIs, not security.

> http://openid.net/specs/openid-connect-core-1_0.html#TokenRequestValidation

This documentation is for token request, not for authorization code grant. This is a different phase in the OAuth 2.0 process.

**Comment by jaredhanson** [comment]
> This documentation is for token request, not for authorization code grant. This is a different phase in the OAuth 2.0 process.

The token request is the second phase of the authorization_code flow, when the code is exchanged for the token.  It is one phase of a single flow, and the ehtire flow is the unit which must be considered from from a security standpoint.  The redirect_uri is verified here because it is important for security.

I'm going to politely disagree with your assertion that the `redirect_uri` is not required for security.  At this point in the discussion, I've pointed out the relevant issues.  I encourage you to implement what you are suggesting, but also advise you to consider this more deeply.  If the `redirect_uri` can be modified at any point between the client's authorization request, the users authorization response, and the client's exchange of the code for a token - that is a security hole, I promise you.  It would be great to not use cookies, but in order to ensure the security, the `redirect_uri` must not be able to be tampered with by the user.

**Comment by mrvisser** [comment]
> The token request is the second phase of the authorization_code flow, when the code is exchanged for the token.

Yes but it is not dependent on user session state and it does not use the `transaction_id` in the oauth2orize implementation. I'm not trying to change anything in the implementation of the token request.

> At this point in the discussion, I've pointed out the relevant issues.

With all due respect, you have pointed out issues, and I have addressed them directly with the fact that clients have registered redirect URIs on the oauth2server side. Unfortunately, I cannot get acknowledgement of that implementation detail and discuss the security issues that still occur when registered redirect URIs exist. I assure you, open redirect attack is not an issue with that feature, so what is left? An example may help.

>  If the redirect_uri can be modified at any point between the client's authorization request, the users authorization response, and the client's exchange of the code for a token - that is a security hole, I promise you.

1. Client's token exchange definitely should have its redirect_uri validated, I'm not arguing against that, however the validation for the exchange phase is not bound to user session state. I am not asking to change this portion of the workflow
2. I'm actually failing to see how the client redirectURI can be tampered with in between the user redirect and the auth code grant POST request (unless the user being granted the code tampers it themself, which they can do any way by invoking their own client grant redirect). The reception of the redirect and the POST is controlled by the authorization server. Even if it does get tampered with, it's still not an open redirect attack as it will still be validated against a **registered valid Redirect URI** in the grant POST request. Aside from open redirect attack, what else is dangerous?

I don't think it's worth spending the time to update the grant handling if I can't get you to you buy in to that portion. In general, it may be better to have a larger piece of work that adds support for redirect URIs along with it to ensure that oauth2orize doesn't provide the ability to ignore both vectors of security: registered URIs and client authenticity -- which I unfortunately do not have the resources to complete for my narrow OAuth use-case.

That said, I think I'll pass on putting dev effort into this issue for now and work around the grant flow with some custom code. I'll still be using the other aspects of oauth2orize, which I want to be completely clear that I am very grateful for :) Cheers!

**Comment by jaredhanson** [comment]
> Unfortunately, I cannot get acknowledgement of that implementation detail and discuss the security issues that still occur when registered redirect URIs exist.

> Client's token exchange definitely should have its redirect_uri validated, I'm not arguing against that, however the validation for the exchange phase is not bound to user session state. 

If the client has multiple registered redirect URIs, it must send the one it is using in the request to disambiguate, which must be stored somewhere in order to validate the subsequent exchange of the code for the token.  In this is not stored in the session while the user is presented with the authorization dialog, where do you propose to store it?

**Comment by jaredhanson** [comment]
To set aside the issue of redirect URIs for a moment, let's imagine a stateless scenario.  I'm not sure how you intended to go about this, but I'll imagine an "easy" approach for the sake of discussion.

- Client 123 submits an authorization request:

```
/authorize?client_id=123
```

- OAuth server presents a dialog, with the client_id from the request in a hidden form field, essentially serializing the transaction into the form itself (without binding it securely to the session in which it was initiated).

```
<input name="client_id" type="hidden" value="123">
```

- Client is presented with a dialog to approve access for client 123.

- Malicious script inside user's browser rewrites the form tag with their own client_id.

```
<input name="client_id" type="hidden" value="666">
```

- Client clicks allow, thinking that they are allowing client 123, when in fact they are now allowing client 666.


As I said, I am all for stateless operation.  However, you must still securely bind the approval to the request that initiated it.  The above obviously would not cut it, and I haven't seen the exact details of what you propose.  I'd be thrilled if you could detail them here, or submit a pull request with a secure implementation, in which case I would gladly merge.

**Comment by mrvisser** [comment]
I was writing a proposal that looked something like this. You put the parameters into a form.

If you have malicious scripts running on the user's pages, why worry about OAuth authentication? The scripts already have full access to perform actions on behalf of users already? That includes phishing URLs sending the user to an auth page of client 666, and rewriting the content of the page to look like it someone else's client. Everything is already compromised if you have a malicious script on your authorization page.

**Comment by jaredhanson** [comment]
> Everything is already compromised if you have a malicious script on your authorization page.

You are kidding, right?  One of the points of proper security on the server side is to protect against the case when clients have been compromised.  It is entirely possible to detect when this "123" to "666" rewrite occurred and warn the user that they are under attack.  In fact, that is exactly what this check does: https://github.com/jaredhanson/oauth2orize/blob/master/lib/middleware/transactionLoader.js#L45

**Comment by mrvisser** [comment]
How do you protect when a malicious script just redirects the user from the 123 auth page to the 666 auth page, and rewrites the content to look like that 123 client? They get their own transaction is and its equivalent.

**Comment by jaredhanson** [comment]
You understand that with the above detailed "form post serialization" all a malicious entity would have to do is trick a user into submitting a form post to authorize a malicious application.  The user's browser would not even have to be compromised, and the user would never know what they have done.  This is a well-understood attack that has occurred many times before.

It is prevented by binding the initial authorization request to the session in which it was initiated.  The protection happens in `oauth2orize` because the transaction_id is bound to the session.  It *is* possible to do this without cookies, but that first requires the server cryptographically signing the initial authorization request parameters before handing it to the client, in order to prevent just such an attack.

**Comment by jaredhanson** [comment]
> How do you protect when a malicious script just redirects the user from the 123 auth page to the 666 auth page, and rewrites the content to look like that 123 client?

To be more specific.  In `oauth2orize`, the client ID is not serialized into the form (only the transaction id is).  Thus, the malicious entity cannot rewrite the the client ID.  If the transaction_id were rewritten, the malicious authorization attempt would be rejected because it would no longer match what has been bound to the session.

**Comment by mrvisser** [comment]
I'm referring to *redirect*, not *rewrite*. 

A malicious script can just *redirect* you to the auth page for client 666, then when it loads rewrite the information on the page to look like the page you came from (123) and gain unexpected authorization that way. A transaction_id I'm afraid doesn't save you from XSS in OAuth 2.0. You just have to make sure your auth page doesn't have XSS vulnerabilities similar to the rest of your application. But if your app has XSS vulnerabilities, who needs to target OAuth? Just use the user's web session :)

For CSRF attacks (the remote POST request vector you mention), similar to XSS, any application is going to need a wide solution for this, and the OAuth library, while convenient to have an option for lightweight apps, IMHO doesn't have to enforce its own (stateful) ad-hoc solution to that problem.

Apologies for the brevity.

**Comment by jaredhanson** [comment]
Thanks for the discussion. You know my stance with regard to merging patches that weaken security.  Good luck with your implementation

**Comment by mrvisser** [comment]
You too, thanks. Sorry we couldn't find a way to improve anything with all this discussion, but I think it's a sign things are already very good. Cheers.

**Comment by KidkArolis** [comment]
@jaredhanson do you know of any resources discussing this secure binding of authorization request params? You mentioned that "This is a well-understood attack that has occurred many times before to insecure implementations", but I couldn't find any resources on this.

I'm considering disabling transactions completely and serialising all the requests params into the form like @mrvisser suggested.

Or alternatively, I'm considering serializing the request params into a signed jwt token that's embedded into the form. This could enable a completely stateless implementation (if I also stored the user authentication in a very short lived jwt token in a cookie (so that refreshing the authorization page still works)).

**Comment by jaredhanson** [comment]
> I'm considering disabling transactions completely and serialising all the requests params into the form like @mrvisser suggested.

**Comment by jaredhanson** [comment]
> I'm considering disabling transactions completely and serialising all the requests params into the form like @mrvisser suggested.

Please do not do this.  As I discussed, that is insecure.  If you are considering this, you probably shouldn't be writing OAuth servers.

> Or alternatively, I'm considering serializing the request params into a signed jwt token that's embedded into the form.

**Comment by mrvisser** [comment]
@KidkArolis 

> @jaredhanson do you know of any resources discussing this secure binding of authorization request params? You mentioned that "This is a well-understood attack that has occurred many times before to insecure implementations", but I couldn't find any resources on this.

I believe what is being referred to there is the [CSRF attack](https://en.wikipedia.org/wiki/Cross-site_request_forgery). If your goal is to get rid of the state baked in by the `transaction_id`, then there are stateless CSRF solutions that could suffice in its place for the CRSF part. A signed request/JWT is one such option that I think would do the trick.

**Comment by KidkArolis** [comment]
Thanks for the speedy responses!

Specifically, my question is exactly that - does transaction_id here act purely as a CSRF prevention, or is there some other attack it can prevent? I suppose there's also that XSS issue @jaredhanson was describing above, but I was trying to understand why @mrvisser wasn't convinced ;)

Or in other words, do I still need transaction_id stuff if I already have CSRF tokens in place.

I suppose it can't hurt to layer in more security!

**Comment by jaredhanson** [comment]
> does transaction_id here act purely as a CSRF prevention, or is there some other attack it can prevent?

**Comment by jaredhanson** [comment]
does transaction_id here act purely as a CSRF prevention, or is there some other attack it can prevent?

Yes.  Suppose you implement an OAuth server, and the user has multiple browser windows open.  In window A, they click a link to start an OAuth transaction.  Let's say it prompts them for a password, which they don't remember.   They decide to switch to window B, and click a link to start another transaction.  That, again, prompts them for the password, so the user decides to go figure out what it is.  Once they know, they go back to each window, enter the password and proceed with completing the transactions.

XSRF, is of course important for OAuth servers, and the transaction_id does provide some degree of support for preventing attacks.  However, its primary purpose is to support multiple, simultaneous transactions, which XSRF alone cannot do.

**Comment by KidkArolis** [comment]
Ok, thanks, I think I get it fully now.

Just wanted to point out (like @mrvisser said earlier), you can solve the "multiple user journey" problem by simply serializing the GET params into the form, e.g. that's what GitHub does:

```html
<form accept-charset="UTF-8" action="/login/oauth/authorize" data-form-nonce="1236d33ed1755cc45211c" method="post">
  <div style="margin:0;padding:0;display:inline">
    <input name="utf8" type="hidden" value="&#x2713;" />
    <input name="authenticity_token" type="hidden" value="hJy1cs2Bt9Xes+zBbH3Mb/ikd8lw/eB2EZAlVSMf3VbRj56g==" />
  </div>
  <p>
    <input class="form-control" id="client_id" name="client_id" type="hidden" value="b68f04bdff231" />
    <input class="form-control" id="redirect_uri" name="redirect_uri" type="hidden" value="https://waffle.io/github-callback" />
    <input class="form-control" id="type" name="type" type="hidden" />
    <input class="form-control" id="state" name="state" type="hidden" value="CSmpGTxdURNXPMi" />
    <input class="form-control" id="scope" name="scope" type="hidden" value="public_repo,read:org,user:email" />
    <input class="form-control" id="org_policy" name="org_policy" type="hidden" value="1" />
    <button data-ga-click="Oauth, oauth application authorized, oauth_application_id:52078; listing_id:22; came_from_integrations_directory:false;" type="submit" name="authorize" value="1" tabindex="1" class="btn btn-primary">Authorize application</button>
  </p>
</form>
```

They serialize all of the GET params including the client_id into the form instead of using this transaction method. Seems like that could make oauth2rize simpler, but I understand this might not be in your interest.

They do, however, have the authenticity_token in there which is different every time I refresh the page, which is probably the Rails CSRF prevention token.

Anyways, thanks for the discussion. Security is quite a fascinating topic. For example, I'm now trying to figure out how to store client_secret and access_token securely in the DB, e.g. I can't just bcrypt access_tokens since that makes it impossible to look them up because of the salt, so I'm considering using bcrypt with the same salt value for all access tokens. But this is getting offtopic ;)
