### ISSUE TITLE
Accessing scope in server.authorization()

### ISSUE THREAD

**Issue by DaAwesomeP** [jaredhanson/oauth2orize#139]
In the same function that I am using (successfully) to verify the redirectURI and clientID, I would like to verify the requested scope. I know that I can do this by my own verification method against my database, but how can I access the requested scope from that function? The only parameters that it gives are the clientID (which I can then use the find the client's approved scope in my database) and the redirectURI.

```js
server.authorization(function(clientID, redirectURI, callback) {
  // No way to access requested scope!
});
```
I will also need to access the requested scope later with grant code and exchange code, but this is the first step.

**Comment by jaredhanson** [comment]
Use the immediate mode callback for scope verification.

**Comment by DaAwesomeP** [comment]
@jaredhanson  Could you please give an example? I'm not sure what you mean.

**Comment by jaredhanson** [comment]
```
server.authorization(function(clientID, redirectURI, callback) {
  // validate redirect uri belongs to client
}, function(client, user, scope, callback) {
  // do other validations and potentially issue an immediate response or not
});
```

The code for this is here:
https://github.com/jaredhanson/oauth2orize/blob/master/lib/middleware/authorization.js#L139
https://github.com/jaredhanson/oauth2orize/blob/master/lib/middleware/authorization.js#L191

**Comment by DaAwesomeP** [comment]
Thanks! Does this method work for `server.grant()` or `oauth2orize.grant.token()` as well?

**Comment by DaAwesomeP** [comment]
@jaredhanson that worked well, but is there also a way to access the requested scope when saving the access tokens?

**Comment by DaAwesomeP** [comment]
[This file](https://github.com/jaredhanson/oauth2orize/blob/master/lib/grant/code.js#L43) references `ares.scope`, but my `ares` only has `{allow: true}` in it.

**Comment by DaAwesomeP** [comment]
I was able to access the scope by adding it to the `server.decision` function:
From:
```js
server.decision()
```
To:
```js
server.decision(function(req, callback) {
  callback(null, { scope: req.oauth2.req.scope });
})
```
