### ISSUE TITLE
What is the purpose of the basic policy on the /token route?

### ISSUE THREAD

**Issue by nickewansmith** [jaredhanson/oauth2orize#147]
Love this project.  I am still trying to understand why the passport basic strategy is needed on the /token route.  The code never runs?  If I remove the basic policy everything still works as expected...is it safe to remove this strategy?  All examples show that it should be there, but I cannot see why so far.

**Comment by jaredhanson** [comment]
It's there to authenticate the client calling the /token endpoint

**Comment by safani** [comment]
Hey @jaredhanson thanks for the quick reply.  I understand that the passport Basic Strategy is supposed to authenticate the client, but I'm just wondering why the callback function never runs?  Maybe I'm missing something, but a console.log in the callback function will never get called, and this is why I'm wondering if it is necessary.

The code in the server.exchange function does run as expected giving me the username/password combo, allowing me to verify if the user exists and the password is correct. For example..

```
server.exchange(oauth2orize.exchange.password(function (client, username, password, scope, done) {
    //code runs fine here
}));
```

But the Basic Strategy callback does not run.  For example..

```
passport.use(new BasicStrategy(
    {
        passReqToCallback: true
    },
    function (req, username, password, done) {
        //code here never runs
    }));
```

Just trying to understand what's going on here a bit better.
