### ISSUE TITLE
How to implement "Client Credentials Grant" oauth2 pattern?

### ISSUE THREAD

**Issue by RaaulCabrera** [jaredhanson/oauth2orize#152]
Hello, I would like to implement "Client Credentials Grant": http://tools.ietf.org/html/rfc6749#section-4.4

I think I should do something like this: https://github.com/jaredhanson/oauth2orize/blob/master/lib/grant/code.js

But I'm confused about what functions I should implement to make it work :confused: 

Many thank's in advance.

**Comment by jaredhanson** [comment]
GitHub Issues are for reporting problems with this library, not the place to ask for support. Closing.

**Comment by mchavarriae** [comment]
So, where I can ask for support then?
