### ISSUE TITLE
Stringified responses

### ISSUE THREAD

**Issue by deefactorial** [jaredhanson/oauth2orize#156]
I'm running into an issue describing and validating the responses of this package because the response is stringified before being sent.

https://github.com/apigee-127/swagger-tools/issues/333#issuecomment-178754063

Is there a specific reason why the response is stringified if the result is a json object ?
Would the output be changed significantly if it wasn't stringified ?

**Comment by jaredhanson** [comment]
It's stringified so it can be sent as the body of an HTTP response.  There's no such thing as sending an object as an HTTP response.
