### ISSUE TITLE
Failed to follow the example

### ISSUE THREAD

**Issue by Exagram** [jaredhanson/oauth2orize#164]
I want to login with the UI, get authenticated by my creds, get back a token, and start accessing a protected resource. I copied the code from the example but did not get a token back when I ran `curl -v -X POST --data "username=sudo&password=sudo" http://127.0.0.1/login`:

```
* timeout on name lookup is not supported
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 11795 (#0)
> POST /login HTTP/1.1
> Host: 127.0.0.1
> User-Agent: curl/7.44.0
> Accept: */*
> Content-Length: 27
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 27 out of 27 bytes
< HTTP/1.1 302 Found
< X-Powered-By: Express
< Location: /
< Vary: Accept
< Content-Type: text/plain; charset=utf-8
< Content-Length: 23
< Date: Fri, 18 Mar 2016 04:15:28 GMT
< Connection: keep-alive
<
Found. Redirecting to /* Connection #0 to host 127.0.0.1 left intact
```

Curious, what CURL output should I get back when I do: `passport.authenticate('local', ...`?

**Comment by jaredhanson** [comment]
You should get exactly what is output. The example works as expected. You need to further understand OAuth, but that is not an issue with this project.
