### ISSUE TITLE
req.user undefined in authorization

### ISSUE THREAD

**Issue by seksity** [jaredhanson/oauth2orize#171]
i try to follow your example,when i use passport.authenticate("basic") it work fine,
Problem when login with passport.authenticate("local") then fineOne username in db, when callback into oauth2Controller.authorization and use console.log(req.user) inside i got all user  in db, 

cause of not found user in decision page, please advice.
Thanks

===== Routes =====
```
> "get": {
>     "/api/oauth2/authorize": [
>         // passport.authenticate("user-basic"),    // ===> Basic Strategy -- if uncomment it work fine
>         login.ensureLoggedIn(),
>         oauth2Controller.authorization
>     ],
> },
> "post": {
>     "/login": passport.authenticate("user-local", {    //===> Local Strategy
>         successReturnToOrRedirect: "/",
>         failureRedirect: "/login"
>     }),
>     "/api/oauth2/decision": [
>        oauth2Controller.decision
>     ],
```

===== oauth2.authorization =====
```
> exports.authorization = [
>     (req, res, next) => {
>         console.log(req.user);
>         next()
>     },
>     server.authorization(function(clientId, redirectUri, callback) {
>         Client.findOne({ clientId: clientId }, function (err, client) {
>             if (err) { return callback(err); }
>             return callback(null, client, redirectUri);
>         });
>     }),
>     function(req, res){
>         res.render('decision', { transactionID: req.oauth2.transactionID, user: req.user, client: req.oauth2.client });
>     }
> ];
```

**Comment by jaredhanson** [comment]
Can you provide details as to what prompted you to close this issue?  If you found a solution, that will help the next person who experiences a similar issue.  Thanks!

**Comment by alekoh** [comment]
I've got the same problem.

Is there any solution for this problem?

Thanks!

**Comment by alekoh** [comment]
Yeah, I solved it like that also,

We were getting an undefined object of type user, so that is where out mistake was.
