### ISSUE TITLE
Custom response object for tokens

### ISSUE THREAD

**Issue by aikssen** [jaredhanson/oauth2orize#176]
I'm using resource owner flow, and I want to return a custom object with my own format and information.
Right now when I implement the token generation process:

```
app.post('/oauth/token',
    passport.authenticate(['basic', 'oauth2-client-password'], { session: false }),
    authServer.token(),
    authServer.errorHandler()
);
```

I must to implement an `issue` function.

```
server.exchange(oauth2orize.exchange.password(issue);
```

The problem is that this `issue` function at the end needs to call a `done` function passing the `access_token`, `refresh_token` and so on. This is named `issued` in `lib/exchange/password.js` inside oauth2orize. This function is executed immediately sending the information through `res` without any chance to customize that response.

There is any way to customize the response from:

```
{ 
    "token_type":"Bearer",
    "access_token": [ACCESS_TOKEN], 
    "refreshToken": [REFRESH_TOKEN],
    "expires_in": 1419356238
}
```

To something else, with a nested json?

Or is possible to access to the `res` object in order to provide the enough customization?

**Comment by xiongyong135** [comment]
I've had the same problem,as a temporary solution, 
I package the /token request in server internal, assembly /token response data format to the call
but it does not look graceful.
hope the author could provide more flexible solution at the bottom, 
Thank you

**Comment by kirrg001** [comment]
+1

**Comment by Zacharysp** [comment]
+1

**Comment by lukasstreit** [comment]
+1

**Comment by himanshuakatalli** [comment]
+1

**Comment by jaredhanson** [comment]
The OAuth 2.0 specification defines what the response should look like, including the `access_token` and `refresh_token` parameters.  If you were to change this, you would no longer be compatible with OAuth 2.0 or client libraries implementing OAuth 2.0.

This toolkit is designed for implementing OAuth 2.0 servers, in a way that is compatible, and therefore does not allow deviation from the specification.

**Comment by aikssen** [comment]
it's really sad to see this topic closed without any change. Let the people decide if want to be 
"compatible" or not.
Long time ago I opened this thread because for my was necessary to include additional information
to the response because a machine to machine authentication requires such kind of payload.
At the end I remove completely your library for that kind of restrictions.

**Comment by jaredhanson** [comment]
As the developer of this library, its my goal to implement and maintain code that is compatible with OAuth 2.0.  I have no interest or incentive in maintaining incompatible code, and so won't be changing anything.

If "the people" want to decide, then they can fork this library and maintain their incompatible changes, or use a different library.

**Comment by jaredhanson** [comment]
I should note, that if you want to include additional information in the response, that can be done by passing a `params` argument when invoking the `issue` callback, here: https://github.com/jaredhanson/oauth2orize/blob/master/lib/exchange/password.js#L120

You cannot change the encoding of the OAuth 2.0 specified parameters `access_token`, `refresh_token`, and `token_type`.
