### ISSUE TITLE
How to return json in decision endpoint

### ISSUE THREAD

**Issue by blanchma** [jaredhanson/oauth2orize#184]
Currently, decision try to do a redirect. I'm using oauth2 as client in a React front-end which means the redirect is something I want to handle myself in the front-end. Is there anyway to handle the response of decision?

**Comment by jaredhanson** [comment]
Can you provide any details as to how you are making OAuth authorization requests, and why JSON would be preferred over redirects?

**Comment by blanchma** [comment]
@jaredhanson I research more and this is not complain with OAuth2 specs. My intention was to return a JSON with the redirect URI there instead of an opaqueredirect.
