### ISSUE TITLE
Is this still maintained ?

### ISSUE THREAD

**Issue by LeoMartinDev** [jaredhanson/oauth2orize#211]

**Comment by nullnox** [comment]
I don't speak for @jaredhanson, but I feel completely comfortable using this module for a few reasons:
* The last commit was in April, which is really not too long ago.
* Not all modules need to be updated constantly. This module does what it sets out to do, and it does it well. Looking at the maintainer's profile, I am confidant that if/when updates are needed (for example, if a new version of node.js necessitates updates for compatibility) that he, or someone else that relies on this module, will take care of it.
* There are a lot of open issues, which at first glance makes it appear like there are many problems to be fixed. But most of them appear to be questions or feature requests; nothing really indicative of a buggy or poor quality module.

**Comment by jaredhanson** [comment]
Thanks @nullnox!
