### ISSUE TITLE
Authorization code is not revoked after exchanging it for token

### ISSUE THREAD

**Issue by tamjidrahat** [jaredhanson/oauth2orize#243]
The authorization code grant does not revoke an authorization code after it is exchanged at the token endpoint. This would allow a client to use the authorization code more than once. This is a violation of RFC 6749 (i.e., OAuth 2.0 standard specification) that states, "If an authorization code is used more than once, the authorization server MUST deny the request ...." This behavior makes the application susceptible to an OAuth authorization code injection attack.

### Expected behavior
The authorization code should be revoked or flagged so that it cannot be used twice. Once the authorization code is successfully used to exchange the access token (location: https://github.com/jaredhanson/oauth2orize/blob/master/lib/exchange/authorizationCode.js), the authorization code should be revoked right away. 

### Actual behavior
The authorization code currently can be used multiple times currently to exchange for an access token.

### Steps to reproduce
Initiate the token request multiple times using the same authorization code value.

**Comment by jaredhanson** [comment]
It is up to the implementor to revoke the authorization code in the `issue` callback, prior to issuing the access token.
