### ISSUE TITLE
Using oauth2orize with JS

### ISSUE THREAD

**Issue by ankitpatial** [jaredhanson/oauth2orize#38]
Hi, 
i want to use the oauth2orize server with JS client. 
So working scenario will be 
- client will call server
- server will auto autorize it and send back the code to client call

so in 2nd step i don't want server to use rediret_uri but juts respond back the code.
i know its not a standard flow of authorisation but i need it.
Is there any way i can use it in js app without any post back ?

**Comment by tamlyn** [comment]
Any update on how to get the redirect URL over AJAX and trigger the redirect on the client side?

**Comment by tamlyn** [comment]
Restating the problem: the `server.decision` endpoint does an HTTP redirect back to the client application which makes it incompatible with applications that do all their communication over AJAX. What I want is for the server to return the redirect URL (e.g. as JSON) and let the JS app send the user to the client application.

In the end what I did is bypass `oauth2orize` for the code generation step:

```
router.post('/oauth/code', /* put passport authentication middleware here */ function(req, res, next) {

	var clientId = req.body.client_id;
	var redirectUri = req.body.redirect_uri;

	/* load oauth client app and check redirect url */

	var code = new Code({
		value: uid(16),
		clientId: clientId,
		redirectUri: redirectUri,
		userId: req.user._id
	});

	code.save()
		.then(function() {
			res.send(code.toJSON());
		}, next);
});
```

The token exchange step happens as usual.

**Comment by jaredhanson** [comment]
This modification is incompatible with OAuth 2.0 and is a potential security risk.

**Comment by tamlyn** [comment]
Why so?

The only difference is that instead of returning the redirect URL in the `Location` header, I am returning it in the response body.

**Comment by jaredhanson** [comment]
Have you read the OAuth 2.0 [RFC](https://tools.ietf.org/html/rfc6749)?

**Comment by jaredhanson** [comment]
By removing the redirect, how does the user get a chance to approve the authorization request?

**Comment by tamlyn** [comment]
I have to admit I haven't read it but this paragraph seems relevant:

> ### HTTP Redirections
> This specification makes extensive use of HTTP redirections, in which the client or the authorization server directs the resource owner's   user-agent to another destination.  While the examples in this
   specification show the use of the HTTP 302 status code, any other   method available via the user-agent to accomplish this redirection is   allowed and is considered to be an implementation detail.

Isn't what I'm doing just using a different method of redirection?

Perhaps I should be clearer as to how the above Express controller fits in to the application. The approve/deny form is shown to the user in the Angular application. Clicking "Deny" sends the user back to the client app with the `?error=access_denied`. Clicking "Approve" does an AJAX request to the server to generate a code then sends the user to the client app with `code=xxxx`.

**Comment by jaredhanson** [comment]
> Isn't what I'm doing just using a different method of redirection?

No.  What they are referring to is using form POST with different endpoints rather than 302 redirects.

> The approve/deny form is shown to the user in the Angular application.

How do you ensure that this is secure?  When the request to your `/oauth/code` endpoint is made, how does your server ensure that the user was actually presented with any dialog and approved it?  How doe the server know what was approved in order to limit the scope or lifetime of the token?

**Comment by tamlyn** [comment]
If we're running on HTTPS we can assume that the page hasn't been tampered with and the user is seeing the application as we intended. Of course they could drop into the console and trigger a request manually but the same goes for any client-server interaction. 

With the normal redirection flow, couldn't you create a hidden iframe and trigger the POST form within it?

**Comment by jaredhanson** [comment]
> If we're running on HTTPS we can assume that the page hasn't been tampered with and the user is seeing the application as we intended.

This is a bad assumption.  A properly implemented authorization server should be able to verify all interactions, and should not trust clients in any way.  What you describe is no longer OAuth 2.0, and as such the security properties are no longer defined (and in fact reduced).  The solution is simply to understand and follow the guidelines of OAuth 2.0.

I'm going to reiterate my statement, and caution you that your approach has security flaws.  For anyone else who comes across this issue, I do not recommend that this approach be taken.

**Comment by jaredhanson** [comment]
As I noted above, the `token` (aka `implicit`) grant type is what is defined by OAuth 2.0 to be used by JavaScript applications running in a browser.

**Comment by TrejGun** [comment]
for everybody who is searching for an answer
here is my solution

```
export default class Login extends Component {
  onSubmit = e => {
    const data = new URLSearchParams(e.target);

    return fetch("/api/login", {
      credentials: "include",
      mode: "cors",
      method: "POST",
      body: data,
    }).then(response => {
      if (response.redirected) {
        window.document.location.href = response.url;
      }
    });
  };

  render() {
    return (
      <form onSubmit={this.onSubmit}>
        <input type="email" name="email" />
        <input type="password" name="password" />
        <button type="submit">Login</button>
      </form>
    );
  }
}
```

same works for `decision` step
