### ISSUE TITLE
A 2-legged example would be very helpful.

### ISSUE THREAD

**Issue by nickpoorman** [jaredhanson/oauth2orize#5]
I'm still trying to wrap my head around oauth. I believe a 2-legged example would be very helpful to myself and anyone else trying to login with something like a simple LocalStrategy.

I think this would be great if I could get it working with Backbone, then I could secure all my api calls that Backbone needs to make.

**Comment by mchavarriae** [comment]
server to server comunication (where is not necessary the user aproval) is the "two-legged" scenario. I want to know if I can implement something like that with this library?
