### ISSUE TITLE
How to proper handle custom scope validation inside exchange definition?

### ISSUE THREAD

**Issue by lexagosto** [jaredhanson/oauth2orize#63]
Hi,

trying to force my clients to specify a valid scope when using `client_credentials` I ended up with something like

```
// register the client_credentials exchange
provider.exchange(oauth2orize.exchange.clientCredentials(function(client, scope, done) {
  if (scope.length <= 0) { // this will also perform more accurate checks
    var err = new oauth2orize.TokenError(
      'Invalid scope: you provided an empty set of scopes',
      'invalid_scope'
    );

    return done(err);
  }
  // ...
  // else end up returning the JSON response
  return done(null, client, "", {scope: scope});
}));
```

Of course I declared my endpoint middlewares including the `errorHandler` as you can see here:

```
accessToken: [ // mapped to /accesstoken
  // perform input data validation before to pass on to OAuth2orize
  accessTokenValidation, 
  // authorize the client by id and password
  passport.authenticate(['oauth2-client-password'], { session: false }),
  // oauth2orize flow
  provider.token(),
  provider.errorHandler()
]
```

By looking at the errorHandler source code I can see it should properly recognize the error given to the "done" callback and set the response accordingly. Also printing that error for debug I can see it gets proper attribute set (status: 400) but to the client it then gets returned with a 500 status.

In case it would help to see the whole source file [here's it](https://gist.github.com/lexagosto/39c33e3c11acab90074a).

How should I handle it? I could perform that validation by myself inside another middleware but it seems more appropriate to handle that kind of stuff inside the exchange itself instead of somewhere else since it regards what the client is required to in order to be issued a valid token.

Thank you,
Alex.

**Comment by jadidian** [comment]
@lexagosto thank you for the solution :thumbsup:
