### ISSUE TITLE
Trying to implement scopes

### ISSUE THREAD

**Issue by yalamber** [jaredhanson/oauth2orize#68]
Hello,  
I am trying to implement scopes with this module. I have setups ready. Now I am a bit confused with the scopes.

My authorization middleware 
```
var authorization = [
    login.ensureLoggedIn(),
    authServer.authorization(function(clientID, redirectURI, scope, done) {
      authModels.AppModel.fromAppKey(clientID, function(err, client) {
        if (err) {
          return done(err);
        }
        if(client.redirect_uri === redirectURI){
          return done(null, client, redirectURI);
        }
        return done(new Error('Redirect uri does not match the registered Redirect Uri for this app.'));
      });
    }),
    function(req, res){
      //get scope descriptions
      if((Array.isArray(req.oauth2.req.scope) && req.oauth2.req.scope.length > 0) ){
        async.map(req.oauth2.req.scope, function(item, callback){
          authModels.AuthScopeModel.fromScope(item, function(err, result){
            callback(err, result);
          });
        }, function(err, results){
          res.render('oauth/dialog', { transactionID: req.oauth2.transactionID, user: req.user, client: req.oauth2.client, scopes: results });
        });
      }
      else{
        //default scope
        authModels.AuthScopeModel.fromScope('profile', function(err, scope){
          res.render('oauth/dialog', { transactionID: req.oauth2.transactionID, user: req.user, client: req.oauth2.client, scopes: [scope] });
        });
      }
    }
  ];
```
Here i pass scopes from request to the dialog box and render the scope asked by application to user in dialog box. 
In oauth/dialog I have scopes in checkbox like this:
```<input type="checkbox" name="scope[]" value="<%= item.scope %>" checked readonly> <%= item.scope_description %>```

Now in decision middleware:
```
 var decision = [
    login.ensureLoggedIn(),
    authServer.decision(function(req, done) {
      var scope = req.scope || ['profile'];
      return done(null, { scope: scope });
    })
  ];
```
Here req.scope is undefined. Should i use req.body.scope instead?

**Comment by nodeit** [comment]
@gokercebeci wouldn't this be `req.body.scope`?

**Comment by gokercebeci** [comment]
It can depends on methods. if you receive the scope parameter with __POST__ you can use `req.body` another way `req.query`.

My usage:

        exports.authorization = [
            login.ensureLoggedIn(),
            server.authorization(function (clientId, redirectUri, scope, callback) {
                Client.findOne({client_id: clientId}, function (err, client) {
                    if (!client) {
                        return callback(null, false);
                    }
                    if (client['app_domains'].indexOf(url.parse(redirectUri).hostname) < 0) {
                        err = new Error('Redirect URI does not match registered redirect URI');
                        err.name = 'Error';
                        err.status = 400;
                        err.code = 400;
                    }
                    if (err) {
                        return callback(err);
                    }
                    return callback(null, client, redirectUri);
                });
            }),
            function (req, res, next) {
                var scope = req.query['scope'].replace(/\s/g, '').split(/,/);
                Token.findOne({
                    clientId: req.oauth2.client.client_id,
                    userId: req.user._id,
                    scope: {$in: scope}
                }, function (err, token) {
                    if (!token) {
                        return res.render('dialog', {
                            transactionID: req.oauth2.transactionID,
                            scope: req.query.scope,
                            user: req.user,
                            client: req.oauth2.client
                        });
                    }
                    if (err) {
                        return next(err);
                    }
                    req.query.transaction_id = req.oauth2.transactionID;
                    next();
                });
            },
            server.decision(function (req, callback) {
                return callback(null, {scope: req.query.scope});
            })
        ];

**Comment by nodeit** [comment]
@gokercebeci Awesome, thanks for the quick response!
