### ISSUE TITLE
How to pass data to allow/deny dialog?

### ISSUE THREAD

**Issue by coolaj86** [jaredhanson/oauth2orize#86]
I'm looking at this function here:
https://github.com/jaredhanson/oauth2orize/blob/master/lib/middleware/authorization.js#L139

And you only assign `oauth2.req` in when `allow` is `true`. Shouldn't it be assigned in both cases?

In my use case I check to see if the scope has new permissions or not.

If the scope does not required new permissions, I pass `allow` as `true`.

If the scope does require permissions that are being requested for the first time, I set `allow` as `false` and pass in an object containing information necessary for `next`ed function, which is the one that renders the allow / deny permission dialog.

I'd like to patch it so that `req.oauth2.res` is set even in the `false` condition, or perhaps another variable name would be better?

I'd be happy to submit a patch, I just need to know your thoughts on how this should be handled.

**Comment by coolaj86** [comment]
The discussion has been had. The pull request is in. Closing this since it's linked to in the Pull Request.

**Comment by aferlim** [comment]
You need to put it in decision flow.
After authorization, that defines decision flow.. before in decision UI:

<form class="was-validated" action="/oauth/authorize" method="POST">...

<button class="btn btn-danger" type="submit" **name="cancel"** value="Deny">Deny</button>
            <button class="btn btn-primary" type="submit" value="Allow">Allow</button>
...

Then in Post:

app.route('/oauth/authorize')
        .get(isLoggedIn, authorization)
        .post(isLoggedIn, require('oauth-config').decision)

oauth-config:

...

module.exports = {
decision: [
server.decision({ cancelField: **'cancel'** }, (req, done) => (
            done(null, { scope: req.body.scope })
        ))
]}
