### ISSUE TITLE
How to remember authorization decisions?

### ISSUE THREAD

**Issue by ralphcallaway** [jaredhanson/oauth2orize#94]
Got this setup and everything is working great except for one "snag".  Everytime a user goes through a new authorization request they have to re "allow" the access. 

I've been scouring the web to figure out what the standard is here.  It seems like there is some differences of opinion on whether a user must authorize access every time or only the first time a client request access.  

My ideal goal is to skip the authorization process completely, as if the user always clicked "allow".  Failing that, only require to click "allow" once for each client.

Currently I'm just auto-submitting the allow button on the decision page, but am hoping there might be a hook I can use to force "allow" in all cases.

Is this even possible? And if so, what's the proper place to splice this in?

**Comment by m-apsolon** [comment]
you, my friend, are a hero! @leejefon

**Comment by sajmons** [comment]
This is really very helpful information! Thank you @leejefon!

**Comment by popasquat89** [comment]
@leejefon You sir, just made my week! This needs to be better documented!

**Comment by TrejGun** [comment]
@leejefon thanks!
